import type { ChecklistItemDef, ChecklistItemType, Obligation } from './types'

/** checklist 建構輔助：ck('對帳', 'RECONCILE', true, 'C-FR-01', '提示') */
export const ck = (
  text: string,
  type: ChecklistItemType,
  required = true,
  control?: string,
  hint?: string,
): Omit<ChecklistItemDef, 'id'> => ({ text, type, required, control, hint })

/** 為每個義務的檢核項目自動編號，避免手動維護 id */
export function withIds(obligationId: string, items: Omit<ChecklistItemDef, 'id'>[]): ChecklistItemDef[] {
  return items.map((it, i) => ({ ...it, id: `${obligationId}#${String(i + 1).padStart(2, '0')}` }))
}

const O = (o: Omit<Obligation, 'checklist'> & { checklist: Omit<ChecklistItemDef, 'id'>[] }): Obligation => ({
  ...o,
  checklist: withIds(o.id, o.checklist),
})

/* ═══════════════ 一、財務會計與財報編製 ═══════════════ */

export const REPORTING_OBLIGATIONS: Obligation[] = [
  O({
    id: 'RPT-MONTH-CLOSE',
    title: '月結帳與管理報表結案',
    area: 'REPORTING',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 6 },
    adjust: 'PREV',
    leadBusinessDays: 4,
    remindDaysBefore: [3, 1],
    owner: 'ACCOUNTING',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 3,
    legalBasis: ['公司內部結帳作業辦法'],
    channel: 'ERP / 合併報表系統',
    outputs: ['試算表', '個體及合併損益表', '管理階層月報'],
    checklist: [
      ck('全部子公司報表包（Reporting Package）收齊並完成幣別換算', 'DOC', true, 'C-FR-01'),
      ck('銀行存款完成銀行調節表，未達帳項逐筆說明', 'RECONCILE', true, 'C-TR-02'),
      ck('應收/應付與關係人往來雙向勾稽，差異為零', 'RECONCILE', true, 'C-FR-02', '母子公司與關係企業往來須雙向確認'),
      ck('存貨帳面與倉儲系統數量勾稽，差異已查明', 'RECONCILE', true, 'C-FR-03'),
      ck('內部交易與未實現損益完成沖銷', 'RECONCILE', true, 'C-FR-04'),
      ck('固定資產折舊、無形資產攤銷已計提', 'CONFIRM', true),
      ck('應計費用、預提獎金與員工酬勞已計提', 'CONFIRM', true),
      ck('外幣資產負債以期末匯率評價，兌換損益已入帳', 'CONFIRM', true, 'C-TR-05'),
      ck('衍生性商品評價（MTM）已取得對手報價並入帳', 'CONFIRM', true, 'C-TR-06'),
      ck('所得稅費用（含遞延）已估算', 'CONFIRM', true),
      ck('執行分析性覆核，重大波動項目已取得說明', 'CONFIRM', true, 'C-FR-05'),
      ck('會計主管覆核並簽署結帳確認表', 'APPROVAL', true),
    ],
    notes: '結帳日建議設在次月第 6 個營業日之前，以保留營收公告與季報編製的緩衝。',
  }),
  O({
    id: 'RPT-MONTHLY-REVENUE',
    title: '每月營運情形（月營收）公告申報',
    area: 'REPORTING',
    category: 'STATUTORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 10 },
    adjust: 'NEXT',
    leadBusinessDays: 3,
    remindDaysBefore: [5, 2, 1],
    owner: 'ACCOUNTING',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 5,
    legalBasis: ['證券交易法第 36 條第 1 項第 3 款'],
    penalty: '證交法第 178 條罰鍰；上市櫃公司另可能遭列處置或變更交易方法',
    channel: '公開資訊觀測站',
    outputs: ['月營收申報表', '重大變動說明（如適用）'],
    checklist: [
      ck('確認合併營收範圍（本月新增/處分子公司已調整）', 'CONFIRM', true, 'C-FR-06'),
      ck('營收數與 ERP 出貨/驗收紀錄勾稽', 'RECONCILE', true),
      ck('本月與上月、去年同月變動幅度分析，超過門檻者備妥說明', 'CONFIRM', true, 'C-FR-05'),
      ck('確認無應先行發布之重大訊息（避免營收公告即為重訊）', 'CONFIRM', true, 'C-CP-01'),
      ck('財務長核准申報數字', 'APPROVAL', true),
      ck('於公開資訊觀測站完成輸入並確認申報成功回條', 'FILING', true),
    ],
  }),
  O({
    id: 'RPT-Q-FS',
    title: '第一、二、三季合併財務報告公告申報',
    area: 'REPORTING',
    category: 'STATUTORY',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 45 },
    adjust: 'NEXT',
    leadBusinessDays: 25,
    remindDaysBefore: [30, 14, 7, 3, 1],
    owner: 'ACCOUNTING',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 5,
    legalBasis: [
      '證券交易法第 36 條第 1 項第 2 款',
      '證券發行人財務報告編製準則',
      '國際財務報導準則（IFRS）第 34 號 期中財務報導',
    ],
    penalty: '逾期未申報：罰鍰、暫停交易、變更交易方法',
    channel: '公開資訊觀測站',
    outputs: ['合併財務報告（經會計師核閱）', '會計師核閱報告', '財務報告申報書'],
    checklist: [
      ck('結帳完成並鎖帳，調整分錄已全數過帳', 'CONFIRM', true, 'C-FR-07'),
      ck('會計師核閱重點事項清單已回覆完畢', 'CONFIRM', true),
      ck('重大會計估計（備抵呆帳、存貨跌價、資產減損、遞延稅資產）已重新評估並留存工作底稿', 'DOC', true, 'C-FR-08'),
      ck('關係人交易彙總表完成，並與附註揭露一致', 'RECONCILE', true, 'C-CP-05'),
      ck('資金貸與、背書保證、衍生性商品部位揭露與申報數一致', 'RECONCILE', true, 'C-TR-07'),
      ck('現金流量表期末現金餘額與資產負債表一致', 'RECONCILE', true, 'C-FR-09'),
      ck('每股盈餘、稀釋 EPS 計算覆核', 'CONFIRM', true),
      ck('期後事項（Subsequent Events）評估至報告日', 'CONFIRM', true, 'C-FR-10'),
      ck('財報附註與前期比較數一致性檢查', 'CONFIRM', true),
      ck('管理階層聲明書已簽署', 'DOC', true),
      ck('審計委員會審議通過', 'APPROVAL', true, 'C-CP-02'),
      ck('董事會通過財務報告', 'APPROVAL', true, 'C-CP-02'),
      ck('公開資訊觀測站完成財報上傳與 XBRL 申報', 'FILING', true),
    ],
    notes: '金融保險等特殊行業另有較短期限，須依主管機關個別規定調整。',
  }),
  O({
    id: 'RPT-ANNUAL-FS',
    title: '年度合併及個體財務報告公告申報',
    area: 'REPORTING',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 3 },
    adjust: 'NEXT',
    leadBusinessDays: 45,
    remindDaysBefore: [60, 30, 14, 7, 3, 1],
    owner: 'ACCOUNTING',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 5,
    legalBasis: [
      '證券交易法第 36 條第 1 項第 1 款',
      '證券發行人財務報告編製準則',
      '會計師查核簽證財務報表規則',
    ],
    penalty: '逾期未申報：罰鍰、停止買賣；財報不實另有民刑事責任',
    channel: '公開資訊觀測站',
    outputs: ['經會計師查核簽證之合併及個體財報', '查核報告（含關鍵查核事項 KAM）', '內部控制制度聲明書（併同）'],
    checklist: [
      ck('年度實地盤點（存貨、固定資產）已完成，差異調整入帳', 'CONFIRM', true, 'C-FR-11'),
      ck('銀行、應收、應付、律師函證回函收齊，未回函者執行替代程序', 'DOC', true, 'C-FR-12'),
      ck('資產減損測試（商譽、無形資產、CGU）完成並留存評價報告', 'DOC', true, 'C-FR-08'),
      ck('遞延所得稅資產可回收性評估（含未來課稅所得預測）', 'DOC', true),
      ck('退休金精算報告已取得並入帳', 'DOC', true),
      ck('關鍵查核事項（KAM）與會計師達成共識', 'CONFIRM', true),
      ck('繼續經營評估（含未來 12 個月資金計畫）', 'CONFIRM', true, 'C-TR-08'),
      ck('新公報（IFRS/IAS 修訂）採用影響已評估並揭露', 'CONFIRM', true),
      ck('關係人交易、背書保證、資金貸與、轉投資明細表完成', 'DOC', true),
      ck('管理階層聲明書與會計師獨立性聲明取得', 'DOC', true),
      ck('審計委員會審議通過財報並作成紀錄', 'APPROVAL', true, 'C-CP-02'),
      ck('董事會通過財報及盈餘分配議案', 'APPROVAL', true, 'C-CP-02'),
      ck('公開資訊觀測站完成申報（含 XBRL）', 'FILING', true),
    ],
  }),
  O({
    id: 'RPT-CPA-COMM',
    title: '簽證會計師季度溝通會議（含審計委員會獨立溝通）',
    area: 'REPORTING',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 40 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [14, 5],
    owner: 'CFO',
    reviewer: 'AUDIT_COMMITTEE',
    approver: 'AUDIT_COMMITTEE',
    severity: 3,
    legalBasis: ['公開發行公司審計委員會行使職權辦法', '審計準則公報「與治理單位之溝通」'],
    outputs: ['會計師溝通議程與紀錄'],
    checklist: [
      ck('會計師提出之未更正錯誤彙總表已檢視', 'CONFIRM', true),
      ck('內部控制缺失（管理建議書）已回覆改善計畫', 'DOC', true, 'C-IC-04'),
      ck('會計師獨立性與非審計服務費用已揭露', 'CONFIRM', true),
      ck('審計委員會與會計師至少一次無管理階層在場之溝通', 'CONFIRM', true, 'C-CP-03'),
    ],
  }),
  O({
    id: 'RPT-ACCT-POLICY',
    title: '會計政策與新公報影響年度評估',
    area: 'REPORTING',
    category: 'INTERNAL',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 11, day: 30 },
    adjust: 'PREV',
    leadBusinessDays: 20,
    remindDaysBefore: [30, 10],
    owner: 'ACCOUNTING',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 3,
    legalBasis: ['證券發行人財務報告編製準則', '金管會認可之 IFRS 版本公告'],
    outputs: ['新公報影響評估報告', '會計政策手冊更新版'],
    checklist: [
      ck('確認次年度適用之 IFRS 版本與新增/修訂公報清單', 'CONFIRM', true),
      ck('逐號評估對本公司之量化與質性影響', 'DOC', true),
      ck('系統與報表格式調整需求已提出', 'CONFIRM', false),
      ck('與簽證會計師確認處理方式', 'CONFIRM', true),
    ],
  }),
]

/* ═══════════════ 二、預算、管理會計與績效 ═══════════════ */

export const FPA_OBLIGATIONS: Obligation[] = [
  O({
    id: 'FPA-MONTH-REVIEW',
    title: '月度經營檢討（實績 vs 預算差異分析）',
    area: 'FPA',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 12 },
    adjust: 'PREV',
    leadBusinessDays: 3,
    remindDaysBefore: [3, 1],
    owner: 'FPA',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 2,
    legalBasis: ['公司內部經營管理制度'],
    outputs: ['經營檢討簡報', '差異分析表', '行動方案追蹤表'],
    checklist: [
      ck('營收、毛利、營業利益與預算差異 ±5% 以上者逐項說明', 'CONFIRM', true),
      ck('費用超支項目取得部門說明與改善方案', 'DOC', true),
      ck('資本支出執行率與預算對比', 'CONFIRM', true),
      ck('現金流量實績與預測差異分析', 'CONFIRM', true),
      ck('上月行動方案追蹤結案情形', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'FPA-ROLLING-FORECAST',
    title: '滾動預測更新（未來 12 個月）',
    area: 'FPA',
    category: 'INTERNAL',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 20 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [10, 3],
    owner: 'FPA',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 3,
    legalBasis: ['公司內部經營管理制度'],
    outputs: ['滾動預測（P&L / 現金流 / 資產負債表）', '情境分析（樂觀/基準/保守）'],
    checklist: [
      ck('業務單位訂單能見度與出貨預估已更新', 'CONFIRM', true),
      ck('原物料價格、匯率、利率假設已更新並列示', 'DOC', true),
      ck('三情境模擬（含保守情境下之資金缺口）已完成', 'DOC', true, 'C-TR-08'),
      ck('若與已公開財測差異重大，評估是否須發布重大訊息', 'CONFIRM', true, 'C-CP-01'),
    ],
  }),
  O({
    id: 'FPA-ANNUAL-BUDGET',
    title: '次年度營運計畫與預算編製（送董事會核定）',
    area: 'FPA',
    category: 'INTERNAL',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 12, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 60,
    remindDaysBefore: [90, 45, 21, 7],
    owner: 'FPA',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公司法第 202 條（公司業務執行由董事會決議）', '公司內部授權辦法'],
    outputs: ['年度營運計畫', '年度預算（損益/現金流/資本支出/人力）', '董事會議案'],
    checklist: [
      ck('策略目標與 KPI 由經營層確認', 'CONFIRM', true),
      ck('各部門預算彙總並完成挑戰會議', 'CONFIRM', true),
      ck('資本支出案逐案附投資效益評估（NPV/IRR/回收期）', 'DOC', true),
      ck('資金需求與融資計畫已配套（含額度是否足夠）', 'CONFIRM', true, 'C-TR-01'),
      ck('稅務影響與有效稅率預估已納入', 'CONFIRM', true),
      ck('董事會核定並作成決議紀錄', 'APPROVAL', true),
    ],
  }),
  O({
    id: 'FPA-CAPEX-REVIEW',
    title: '重大投資案投後績效追蹤（PIR）',
    area: 'FPA',
    category: 'INTERNAL',
    tiers: [],
    period: 'HALF',
    due: { type: 'DAYS_AFTER', days: 45 },
    adjust: 'PREV',
    leadBusinessDays: 15,
    remindDaysBefore: [14, 5],
    owner: 'FPA',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['公開發行公司取得或處分資產處理準則（投資後續評估）', '公司內部投資管理辦法'],
    outputs: ['投後績效追蹤報告'],
    checklist: [
      ck('逐案比較實際效益與原評估假設', 'DOC', true),
      ck('達成率低於 80% 之案件提出檢討與對策', 'CONFIRM', true),
      ck('轉投資事業之財務狀況與減損跡象評估', 'CONFIRM', true, 'C-FR-08'),
      ck('向董事會報告', 'APPROVAL', true),
    ],
  }),
]

/* ═══════════════ 三、資金、外匯與融資 ═══════════════ */

export const TREASURY_OBLIGATIONS: Obligation[] = [
  O({
    id: 'TRE-13W-CASHFLOW',
    title: '13 週滾動現金流量預測更新',
    area: 'TREASURY',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 5 },
    adjust: 'PREV',
    leadBusinessDays: 2,
    remindDaysBefore: [2],
    owner: 'TREASURY',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['公司內部資金調度辦法'],
    outputs: ['13 週現金流量預測表', '資金缺口與因應方案'],
    checklist: [
      ck('應收帳款回收預估依客戶別更新（含逾期客戶調整）', 'CONFIRM', true, 'C-RK-02'),
      ck('應付帳款、薪資、稅款、股利等大額支出已排入', 'CONFIRM', true),
      ck('借款到期與還本付息排程已納入', 'CONFIRM', true),
      ck('最低現金水位（Minimum Cash Buffer）未被突破，否則提出因應', 'CONFIRM', true, 'C-TR-03'),
      ck('未動用額度足以涵蓋保守情境缺口', 'CONFIRM', true, 'C-TR-01'),
    ],
  }),
  O({
    id: 'TRE-BANK-RECON',
    title: '全集團銀行帳戶與額度盤點',
    area: 'TREASURY',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 8 },
    adjust: 'PREV',
    leadBusinessDays: 3,
    remindDaysBefore: [3],
    owner: 'TREASURY',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['公司內部資金管理辦法'],
    outputs: ['銀行帳戶總表', '額度使用率表', '受限制資產明細'],
    checklist: [
      ck('銀行對帳單/餘額證明全數取得', 'DOC', true, 'C-TR-02'),
      ck('帳戶印鑑卡與授權人清冊與現況相符（離職人員已註銷）', 'CONFIRM', true, 'C-TR-04'),
      ck('網銀權限與交易限額覆核，維持交易/覆核分離', 'CONFIRM', true, 'C-TR-04'),
      ck('質押、備償專戶等受限制資產已標示並於財報揭露', 'CONFIRM', true),
      ck('單一銀行存款集中度符合政策上限', 'CONFIRM', true, 'C-RK-03'),
    ],
  }),
  O({
    id: 'TRE-FX-HEDGE',
    title: '外匯曝險衡量與避險部位檢討',
    area: 'TREASURY',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 10 },
    adjust: 'PREV',
    leadBusinessDays: 3,
    remindDaysBefore: [3],
    owner: 'TREASURY',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['公開發行公司取得或處分資產處理準則（從事衍生性商品交易）', '公司內部衍生性商品交易處理程序'],
    outputs: ['外幣淨部位表', '避險比率報告', '衍生性商品部位與評價表'],
    checklist: [
      ck('各幣別資產負債淨部位與預期現金流曝險已彙總', 'DOC', true, 'C-TR-05'),
      ck('避險比率落於政策區間內', 'CONFIRM', true, 'C-TR-06'),
      ck('未實現評價損失未超過內部辦法所定上限', 'CONFIRM', true, 'C-TR-06'),
      ck('交易對手集中度與信用風險評估', 'CONFIRM', true),
      ck('交易人員與確認/交割人員職責分離', 'CONFIRM', true, 'C-TR-04'),
      ck('依內部辦法向董事會/審計委員會報告部位', 'APPROVAL', true),
    ],
  }),
  O({
    id: 'TRE-LENDING-ENDORSE-FILING',
    title: '資金貸與及背書保證餘額公告申報',
    area: 'TREASURY',
    category: 'REGULATORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 10 },
    adjust: 'NEXT',
    leadBusinessDays: 3,
    remindDaysBefore: [5, 2, 1],
    owner: 'TREASURY',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 5,
    legalBasis: ['公開發行公司資金貸與及為他人背書保證處理準則第 22 條'],
    penalty: '未依規定公告申報或超限：證交法罰鍰、董事責任',
    channel: '公開資訊觀測站',
    outputs: ['資金貸與餘額申報表', '背書保證餘額申報表'],
    checklist: [
      ck('逐筆核對貸與/背書保證對象、金額、期間與董事會決議一致', 'RECONCILE', true, 'C-TR-07'),
      ck('總額及對單一企業限額未超過公司辦法所定上限', 'CONFIRM', true, 'C-TR-07'),
      ck('超限或有損失之虞者已依規定提列備抵並揭露', 'CONFIRM', true),
      ck('與財報揭露數、帳列數三方一致', 'RECONCILE', true),
      ck('公開資訊觀測站完成申報', 'FILING', true),
    ],
  }),
  O({
    id: 'TRE-DERIVATIVE-FILING',
    title: '衍生性商品交易部位公告申報',
    area: 'TREASURY',
    category: 'REGULATORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 10 },
    adjust: 'NEXT',
    leadBusinessDays: 3,
    remindDaysBefore: [5, 2],
    owner: 'TREASURY',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['公開發行公司取得或處分資產處理準則'],
    channel: '公開資訊觀測站',
    outputs: ['衍生性商品交易部位申報表'],
    checklist: [
      ck('未沖銷部位名目本金與評價損益完成彙整', 'DOC', true),
      ck('評價來源（銀行報價/評價模型）已留存', 'DOC', true),
      ck('與帳列公允價值一致', 'RECONCILE', true),
      ck('公開資訊觀測站完成申報', 'FILING', true),
    ],
  }),
  O({
    id: 'TRE-COVENANT',
    title: '融資契約財務約定（Covenant）檢核與銀行團回報',
    area: 'TREASURY',
    category: 'CONTRACTUAL',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 60 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [21, 7, 3],
    owner: 'TREASURY',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 5,
    legalBasis: ['聯合授信合約 / 個別授信約定書之財務比率條款'],
    penalty: '違反財務約定可能構成違約事由，觸發加速到期（Cross Default）',
    outputs: ['Covenant 檢核表', '致銀行團財務比率證明書'],
    checklist: [
      ck('依合約定義（非財報定義）計算各項財務比率', 'RECONCILE', true, 'C-TR-09', '合約常自訂 EBITDA、淨值、有息負債之定義'),
      ck('比率結果與紅線比較，緩衝不足者提前研擬對策', 'CONFIRM', true, 'C-TR-09'),
      ck('如有違反或即將違反，於合約期限內通知銀行並洽談豁免（Waiver）', 'CONFIRM', true),
      ck('依合約期限提交財報與比率證明書予管理行', 'FILING', true),
      ck('向財務長報告 covenant 緩衝趨勢', 'APPROVAL', true),
    ],
  }),
  O({
    id: 'TRE-CREDIT-LINE',
    title: '銀行往來與授信額度年度檢討',
    area: 'TREASURY',
    category: 'INTERNAL',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 10, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 30,
    remindDaysBefore: [30, 10],
    owner: 'TREASURY',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公司內部資金管理辦法'],
    outputs: ['授信額度總表', '銀行往來策略建議'],
    checklist: [
      ck('次年度資金需求（含資本支出、還本、股利）已估算', 'CONFIRM', true),
      ck('現有額度到期日分散，避免集中續約風險', 'CONFIRM', true),
      ck('未動用額度可涵蓋至少 3 個月營運資金需求', 'CONFIRM', true, 'C-TR-01'),
      ck('借款成本與擔保條件與市場行情比較', 'CONFIRM', true),
      ck('提報董事會核定次年度融資計畫與額度授權', 'APPROVAL', true),
    ],
  }),
]
