import type { ChecklistItemDef, Obligation } from './types'
import { ck, withIds } from './obligations.core'

const O = (o: Omit<Obligation, 'checklist'> & { checklist: Omit<ChecklistItemDef, 'id'>[] }): Obligation => ({
  ...o,
  checklist: withIds(o.id, o.checklist),
})

/* ═══════════════ 五、法遵、公司治理與資訊揭露 ═══════════════ */

export const COMPLIANCE_OBLIGATIONS: Obligation[] = [
  O({
    id: 'CMP-INSIDER-HOLDING',
    title: '內部人持股異動彙總申報',
    area: 'COMPLIANCE',
    category: 'STATUTORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 15 },
    adjust: 'NEXT',
    leadBusinessDays: 5,
    remindDaysBefore: [7, 3, 1],
    owner: 'STOCK_AFFAIRS',
    reviewer: 'LEGAL',
    approver: 'CFO',
    severity: 5,
    legalBasis: ['證券交易法第 25 條第 2 項', '證券交易法第 22-2 條（股權轉讓）'],
    penalty: '證交法第 178 條罰鍰；公司治理評鑑扣分',
    channel: '公開資訊觀測站',
    outputs: ['董事、監察人、經理人及持股 10% 以上股東持股變動表'],
    checklist: [
      ck('內部人名冊已更新（新任/離任董監經理人於異動時即時更新）', 'CONFIRM', true, 'C-CP-04'),
      ck('取得股務代理機構之持股異動明細並逐人核對', 'RECONCILE', true),
      ck('股票設質、解質、質權變動已納入', 'CONFIRM', true),
      ck('依第 22-2 條之轉讓（事前申報、市場交易限制）已合規', 'CONFIRM', true),
      ck('全體董事（或董事+監察人）持股成數符合法定最低成數', 'CONFIRM', true, 'C-CP-06'),
      ck('公開資訊觀測站完成申報', 'FILING', true),
    ],
    notes: '內部人應於每月 5 日前將上月異動情形送交公司，公司彙總後於 15 日前申報。',
  }),
  O({
    id: 'CMP-BOARD-MEETING',
    title: '董事會定期召開（每季至少一次）',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 0 },
    adjust: 'PREV',
    leadBusinessDays: 15,
    remindDaysBefore: [21, 10, 7],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公司法第 203-1 條', '公開發行公司董事會議事辦法'],
    channel: '議事錄留存；重要決議依規定發布重大訊息',
    outputs: ['開會通知與議程', '議案資料', '董事會議事錄', '重大訊息（如適用）'],
    checklist: [
      ck('開會通知連同議程於 7 日前發出（緊急情事除外）', 'DOC', true, 'C-CP-02'),
      ck('議案資料齊備並提前送達董事', 'DOC', true),
      ck('利害關係董事之利益迴避已辨識並於議事錄載明', 'CONFIRM', true, 'C-CP-07'),
      ck('應經審計委員會同意事項已先行提報審計委員會', 'CONFIRM', true),
      ck('獨立董事出席與反對/保留意見已完整記錄', 'CONFIRM', true),
      ck('會議錄音/錄影留存至少 5 年', 'DOC', true),
      ck('議事錄於會後 20 日內分發各董事', 'DOC', true),
      ck('達重大訊息標準之決議於規定時限內發布', 'FILING', true, 'C-CP-01'),
    ],
  }),
  O({
    id: 'CMP-AUDIT-COMMITTEE',
    title: '審計委員會定期召開（每季至少一次）',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC', 'EMERGING'],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 0 },
    adjust: 'PREV',
    leadBusinessDays: 15,
    remindDaysBefore: [21, 10, 7],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'AUDIT_COMMITTEE',
    severity: 4,
    legalBasis: ['證券交易法第 14-5 條', '公開發行公司審計委員會行使職權辦法'],
    outputs: ['審計委員會議事錄'],
    checklist: [
      ck('證交法第 14-5 條應經審計委員會同意事項已全數提案', 'CONFIRM', true, 'C-CP-03'),
      ck('內部稽核報告已提送並由委員會查閱', 'DOC', true, 'C-IC-03'),
      ck('簽證會計師出席說明財報與查核發現', 'CONFIRM', true),
      ck('內部控制有效性、法令遵循情形之報告已提出', 'DOC', true),
      ck('未經審計委員會通過而由全體董事三分之二以上同意者，已於議事錄與年報揭露', 'CONFIRM', false),
    ],
  }),
  O({
    id: 'CMP-COMP-COMMITTEE',
    title: '薪資報酬委員會召開（每年至少二次）',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'HALF',
    due: { type: 'DAYS_AFTER', days: 0 },
    adjust: 'PREV',
    leadBusinessDays: 20,
    remindDaysBefore: [21, 10],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['證券交易法第 14-6 條', '股票上市或於證券商營業處所買賣公司薪資報酬委員會設置及行使職權辦法'],
    outputs: ['薪資報酬委員會議事錄', '董監經理人薪酬政策評估報告'],
    checklist: [
      ck('董事、監察人及經理人之績效評估與薪資報酬政策定期檢討', 'CONFIRM', true),
      ck('薪酬與績效、風險之關聯性已評估（避免誘使追求超出風險胃納之行為）', 'CONFIRM', true),
      ck('員工酬勞、董事酬勞分派比例符合章程', 'CONFIRM', true),
      ck('建議提報董事會決議', 'APPROVAL', true),
    ],
  }),
  O({
    id: 'CMP-AGM',
    title: '股東常會召開全流程',
    area: 'COMPLIANCE',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 6 },
    adjust: 'PREV',
    leadBusinessDays: 90,
    remindDaysBefore: [120, 90, 60, 30, 21, 7],
    owner: 'STOCK_AFFAIRS',
    reviewer: 'LEGAL',
    approver: 'BOARD',
    severity: 5,
    legalBasis: [
      '公司法第 170 條（每會計年度終了後 6 個月內召開）',
      '公司法第 165 條（股東常會前 60 日停止過戶）',
      '公司法第 172 條（常會 30 日前通知）',
      '公開發行公司股東會議事手冊應行記載及遵行事項辦法',
    ],
    penalty: '未依期限召開：公司法罰鍰；程序瑕疵可能導致決議得撤銷',
    channel: '公開資訊觀測站 / 股務代理機構',
    outputs: ['股東會議事手冊', '年報', '議事錄', '各項議案與表決結果'],
    checklist: [
      ck('董事會決議召開日期、地點及股東會議案（含盈餘分配）', 'APPROVAL', true),
      ck('公告停止過戶期間（常會開會前 60 日內）', 'FILING', true, 'C-CP-08'),
      ck('受理股東提案（持股 1% 以上，公告受理期間不少於 10 日）', 'CONFIRM', true),
      ck('董事選舉年度之候選人提名審查作業完成', 'CONFIRM', false),
      ck('開會通知、委託書及議事手冊於常會 30 日前寄發／公告', 'DOC', true, 'C-CP-08'),
      ck('議事手冊及會議補充資料於開會 21 日前上傳公開資訊觀測站', 'FILING', true),
      ck('年報於股東常會開會前備妥並寄發／上傳', 'DOC', true),
      ck('電子投票平台開放（法定應採用者）並於開會 2 日前截止', 'CONFIRM', true),
      ck('會場報到、表決票務與計票作業（含監票人）已安排', 'CONFIRM', true),
      ck('議事錄於會後 20 日內分發股東並公告申報', 'FILING', true),
      ck('股東會決議事項之後續執行（變更登記、除息基準日）已排程', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'CMP-ANNUAL-REPORT',
    title: '年報編製、寄發與申報',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 5, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 45,
    remindDaysBefore: [60, 30, 14, 7],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公開發行公司年報應行記載事項準則'],
    channel: '公開資訊觀測站',
    outputs: ['年報（中文本，必要時英文本）'],
    checklist: [
      ck('公司治理報告（董事會運作、獨董職責、內控聲明）內容更新', 'DOC', true),
      ck('董監經理人酬金揭露級距正確', 'CONFIRM', true),
      ck('財務資訊與經審計財報一致', 'RECONCILE', true),
      ck('風險事項、關係人交易、資金貸與背書保證揭露完整', 'CONFIRM', true),
      ck('與永續報告書、法說會資料口徑一致', 'CONFIRM', true, 'C-IR-02'),
      ck('董事長及會計主管簽章', 'APPROVAL', true),
      ck('股東常會前寄發／公告，並上傳公開資訊觀測站', 'FILING', true),
    ],
  }),
  O({
    id: 'CMP-MATERIAL-INFO',
    title: '重大訊息即時發布（事件驅動）',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC', 'EMERGING'],
    period: 'EVENT',
    due: { type: 'DAYS_AFTER', days: 0 },
    adjust: 'NONE',
    leadBusinessDays: 0,
    remindDaysBefore: [],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 5,
    legalBasis: [
      '證券交易法第 36 條第 3 項',
      '臺灣證券交易所（證券櫃檯買賣中心）對有價證券上市（櫃）公司重大訊息之查證暨公開處理程序',
    ],
    penalty: '延遲或不實發布：違約金、罰鍰，並可能衍生內線交易調查',
    channel: '公開資訊觀測站（重大訊息專區）',
    outputs: ['重大訊息公告'],
    checklist: [
      ck('判斷是否屬應公告事項（財務業務、訴訟、資產、人事、其他重大影響）', 'CONFIRM', true, 'C-CP-01'),
      ck('於事實發生日起算之規定時限內發布（原則為次一營業日交易時間開始前 2 小時內）', 'FILING', true),
      ck('發布前之消息知悉者名單已建立，並提示內線交易禁止', 'DOC', true, 'C-CP-09'),
      ck('內容經法務與財務長覆核，數字與後續財報一致', 'APPROVAL', true),
      ck('必要時安排記者會或補充公告', 'CONFIRM', false),
    ],
    notes: '事件驅動義務不排入行事曆，但列為常備 SOP 與稽核抽核對象。',
  }),
  O({
    id: 'CMP-ASSET-TXN',
    title: '取得或處分資產、關係人交易之公告申報（事件驅動）',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: [],
    period: 'EVENT',
    due: { type: 'DAYS_AFTER', days: 2 },
    adjust: 'NONE',
    leadBusinessDays: 0,
    remindDaysBefore: [],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 5,
    legalBasis: ['公開發行公司取得或處分資產處理準則'],
    channel: '公開資訊觀測站',
    outputs: ['取得或處分資產公告', '不動產估價報告 / 會計師意見書（如適用）'],
    checklist: [
      ck('判斷是否達公告標準（交易金額達實收資本額 20%、總資產 10%、或 3 億元等）', 'CONFIRM', true, 'C-CP-10'),
      ck('關係人交易者，取得會計師／專業估價者意見並經審計委員會與董事會通過', 'APPROVAL', true, 'C-CP-05'),
      ck('取得或處分有價證券達一定金額者取得會計師意見', 'DOC', false),
      ck('於事實發生日起 2 日內完成公告申報', 'FILING', true),
      ck('交易條件與董事會決議一致，價金收付已排入資金調度', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'CMP-GOV-EVAL',
    title: '公司治理評鑑資料整備與缺項改善',
    area: 'COMPLIANCE',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 12, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 45,
    remindDaysBefore: [60, 30, 14],
    owner: 'LEGAL',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['公司治理評鑑指標（證交所/櫃買中心公告）'],
    outputs: ['評鑑指標自評表', '缺項改善計畫'],
    checklist: [
      ck('逐項比對當年度評鑑指標與公司實際執行情形', 'DOC', true),
      ck('可於年度結束前補做之指標（英文資訊、董事進修時數、法說會）已完成', 'CONFIRM', true),
      ck('缺項提報董事會並列入次年度改善計畫', 'APPROVAL', true),
    ],
  }),
]

/* ═══════════════ 六、內部控制與內部稽核 ═══════════════ */

export const IC_OBLIGATIONS: Obligation[] = [
  O({
    id: 'IC-AUDIT-REPORT',
    title: '內部稽核報告與追蹤報告交付審計委員會/監察人',
    area: 'IC_AUDIT',
    category: 'REGULATORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 30 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [7, 3],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'AUDIT_COMMITTEE',
    approver: 'AUDIT_COMMITTEE',
    severity: 4,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 13 條'],
    outputs: ['稽核報告', '缺失追蹤改善報告'],
    checklist: [
      ck('本月稽核項目依年度計畫執行完畢', 'CONFIRM', true, 'C-IC-01'),
      ck('稽核報告及工作底稿於查核項目完成之次月底前交付查閱', 'DOC', true, 'C-IC-03'),
      ck('前期缺失改善情形追蹤，逾期未改善者提報', 'CONFIRM', true, 'C-IC-04'),
      ck('重大缺失即時通報審計委員會與董事長', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'IC-SELF-ASSESS',
    title: '各單位內部控制自行評估',
    area: 'IC_AUDIT',
    category: 'REGULATORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 12, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 45,
    remindDaysBefore: [60, 30, 14],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 24 條'],
    outputs: ['各單位自評表', '自評彙總報告'],
    checklist: [
      ck('自評範圍涵蓋全部內部控制循環與子公司', 'CONFIRM', true, 'C-IC-05'),
      ck('自評表由各單位主管簽署，並附佐證抽樣紀錄', 'DOC', true),
      ck('稽核單位覆核自評結果之合理性', 'CONFIRM', true),
      ck('彙總缺失並形成內控聲明書之依據', 'DOC', true),
    ],
  }),
  O({
    id: 'IC-STATEMENT',
    title: '內部控制制度聲明書（董事會通過後公告申報）',
    area: 'IC_AUDIT',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 3 },
    adjust: 'NEXT',
    leadBusinessDays: 30,
    remindDaysBefore: [45, 21, 7, 3],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 5,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 24 條、第 25 條'],
    penalty: '聲明書內容不實：董事長、總經理及相關人員之行政及刑事責任',
    channel: '公開資訊觀測站（併同年度財報）',
    outputs: ['內部控制制度聲明書'],
    checklist: [
      ck('自行評估結果與稽核發現已完整彙整', 'CONFIRM', true, 'C-IC-05'),
      ck('重大缺失是否已於年度終了日前改善完成，據以判斷聲明內容', 'CONFIRM', true),
      ck('聲明書經董事會通過（董事有異議者載明於議事錄）', 'APPROVAL', true),
      ck('由董事長、總經理及內部稽核主管簽名蓋章', 'APPROVAL', true),
      ck('與年度財報同時公告申報', 'FILING', true),
    ],
  }),
  O({
    id: 'IC-AUDIT-PLAN-FILING',
    title: '上年度內部稽核計畫執行情形申報',
    area: 'IC_AUDIT',
    category: 'REGULATORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 2 },
    adjust: 'NEXT',
    leadBusinessDays: 15,
    remindDaysBefore: [21, 7, 3],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'CFO',
    approver: 'AUDIT_COMMITTEE',
    severity: 4,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 22 條'],
    channel: '公開資訊觀測站（內部稽核專區）',
    outputs: ['上年度稽核計畫執行情形申報表'],
    checklist: [
      ck('計畫項目與實際執行逐項比對，未執行者敘明原因', 'RECONCILE', true, 'C-IC-01'),
      ck('申報格式與主管機關規定一致', 'CONFIRM', true),
      ck('於會計年度終了後 2 個月內完成申報', 'FILING', true),
    ],
  }),
  O({
    id: 'IC-DEFICIENCY-FILING',
    title: '上年度內部控制缺失及異常事項改善情形申報',
    area: 'IC_AUDIT',
    category: 'REGULATORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 5 },
    adjust: 'NEXT',
    leadBusinessDays: 20,
    remindDaysBefore: [21, 7, 3],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'CFO',
    approver: 'AUDIT_COMMITTEE',
    severity: 4,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 22 條'],
    channel: '公開資訊觀測站（內部稽核專區）',
    outputs: ['缺失及異常事項改善情形申報表'],
    checklist: [
      ck('逐項列示缺失、改善措施、完成日期與責任單位', 'DOC', true, 'C-IC-04'),
      ck('尚未改善完成者敘明預計完成期限', 'CONFIRM', true),
      ck('於會計年度終了後 5 個月內完成申報', 'FILING', true),
    ],
  }),
  O({
    id: 'IC-NEXT-AUDIT-PLAN',
    title: '次年度內部稽核計畫擬訂並經董事會通過',
    area: 'IC_AUDIT',
    category: 'REGULATORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 12, day: 31 },
    adjust: 'PREV',
    leadBusinessDays: 30,
    remindDaysBefore: [45, 21, 7],
    owner: 'INTERNAL_AUDIT',
    reviewer: 'AUDIT_COMMITTEE',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['公開發行公司建立內部控制制度處理準則第 13 條'],
    outputs: ['次年度稽核計畫（含風險評估結果）'],
    checklist: [
      ck('以風險評估結果決定稽核頻率與範圍，高風險循環優先', 'DOC', true, 'C-IC-02'),
      ck('法定應查核項目（資金貸與、背書保證、衍生性商品、關係人交易、子公司管理）已納入', 'CONFIRM', true),
      ck('子公司稽核安排已納入', 'CONFIRM', true),
      ck('經董事會通過並留存紀錄', 'APPROVAL', true),
    ],
  }),
]

/* ═══════════════ 七、投資人關係與股務 ═══════════════ */

export const IR_OBLIGATIONS: Obligation[] = [
  O({
    id: 'IR-EARNINGS-CALL',
    title: '法人說明會（每年至少一次，季度業績說明）',
    area: 'IR_STOCK',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 50 },
    adjust: 'PREV',
    leadBusinessDays: 15,
    remindDaysBefore: [21, 7, 3],
    owner: 'IR',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 3,
    legalBasis: ['臺灣證券交易所/櫃買中心對上市（櫃）公司召開法人說明會之規定'],
    channel: '公開資訊觀測站（法說會專區）',
    outputs: ['法說會簡報（中/英）', '會議影音或逐字紀錄', '法說會資訊公告'],
    checklist: [
      ck('法說會日期、地點於規定時限前公告', 'FILING', true, 'C-IR-01'),
      ck('簡報內容與已公告財報、重大訊息完全一致，無未公開重大資訊', 'RECONCILE', true, 'C-IR-02'),
      ck('前瞻性陳述已加註警語與假設基礎', 'CONFIRM', true),
      ck('Q&A 預想問答稿經財務長與法務覆核', 'DOC', true),
      ck('會後簡報與影音於規定時限內上傳公開資訊觀測站', 'FILING', true),
      ck('若會中揭露新的重大資訊，同步發布重大訊息', 'CONFIRM', true, 'C-CP-01'),
    ],
  }),
  O({
    id: 'IR-DIVIDEND',
    title: '股利分派作業（董事會擬議至股利發放）',
    area: 'IR_STOCK',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 9 },
    adjust: 'PREV',
    leadBusinessDays: 60,
    remindDaysBefore: [60, 30, 14, 7],
    owner: 'STOCK_AFFAIRS',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: [
      '公司法第 228 條、第 232 條、第 237 條（法定盈餘公積）',
      '公司法第 240 條、第 241 條（授權董事會分派）',
      '公司章程股利政策',
    ],
    outputs: ['盈餘分配表', '除息（權）基準日公告', '股利發放作業'],
    checklist: [
      ck('盈餘分配符合章程股利政策與法定盈餘公積提列規定', 'CONFIRM', true, 'C-IR-03'),
      ck('可分配盈餘計算正確（含前期未分配盈餘、當年度稅後淨利、其他權益調整）', 'RECONCILE', true),
      ck('未分配盈餘加徵 5% 之稅負影響已評估', 'CONFIRM', true),
      ck('董事會（或股東會）決議並發布重大訊息', 'APPROVAL', true),
      ck('除息基準日、停止過戶期間公告與股務作業排程確認', 'FILING', true),
      ck('發放資金已排入現金流量預測並備妥', 'CONFIRM', true),
      ck('股利憑單申報作業已銜接', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'IR-SHAREHOLDER-ANALYSIS',
    title: '股權結構與大股東動向分析',
    area: 'IR_STOCK',
    category: 'INTERNAL',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 30 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [10, 3],
    owner: 'IR',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 2,
    legalBasis: ['公司內部投資人關係管理辦法'],
    outputs: ['股權分散表', '法人持股變動分析'],
    checklist: [
      ck('股權分散表與集保結算所資料核對', 'RECONCILE', true),
      ck('外資、投信、自營商持股變動分析', 'CONFIRM', true),
      ck('大股東質押比率變化追蹤', 'CONFIRM', true, 'C-IR-04'),
      ck('異常股權集中情形提報財務長', 'CONFIRM', true),
    ],
  }),
]

/* ═══════════════ 八、風險管理與保險 ═══════════════ */

export const RISK_OBLIGATIONS: Obligation[] = [
  O({
    id: 'RSK-AR-AGING',
    title: '應收帳款帳齡與客戶授信額度檢討',
    area: 'RISK',
    category: 'INTERNAL',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 15 },
    adjust: 'PREV',
    leadBusinessDays: 5,
    remindDaysBefore: [5, 2],
    owner: 'TREASURY',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['公司內部授信管理辦法', 'IFRS 9 預期信用損失'],
    outputs: ['帳齡分析表', '逾期客戶處理方案', '備抵呆帳評估'],
    checklist: [
      ck('帳齡分析依客戶別產出，逾期 90 天以上者列管', 'DOC', true, 'C-RK-01'),
      ck('超過授信額度之客戶出貨已凍結或經權責核准例外放行', 'CONFIRM', true, 'C-RK-02'),
      ck('客戶信用評等/保險額度（輸出保險、應收帳款承購）已更新', 'CONFIRM', true),
      ck('依 IFRS 9 預期信用損失模型更新備抵呆帳', 'CONFIRM', true),
      ck('單一客戶集中度超過政策上限者提報', 'CONFIRM', true, 'C-RK-03'),
    ],
  }),
  O({
    id: 'RSK-REGISTER-REVIEW',
    title: '風險登錄簿季度覆核與壓力測試',
    area: 'RISK',
    category: 'INTERNAL',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 50 },
    adjust: 'PREV',
    leadBusinessDays: 15,
    remindDaysBefore: [14, 5],
    owner: 'CFO',
    reviewer: 'AUDIT_COMMITTEE',
    approver: 'BOARD',
    severity: 4,
    legalBasis: ['上市上櫃公司治理實務守則（風險管理）', '公司內部風險管理政策'],
    outputs: ['風險登錄簿更新版', '壓力測試結果', '風險管理報告'],
    checklist: [
      ck('既有風險之可能性/衝擊度重新評分', 'CONFIRM', true),
      ck('新增風險（地緣政治、供應鏈、匯率、資安、法規變動）已辨識', 'CONFIRM', true),
      ck('高風險項目之因應措施與責任人已確認', 'CONFIRM', true),
      ck('財務壓力情境（營收 -30%、匯率不利變動、利率上升）之流動性影響已試算', 'DOC', true, 'C-RK-04'),
      ck('每年至少一次向董事會報告風險管理運作情形', 'APPROVAL', true),
    ],
  }),
  O({
    id: 'RSK-INSURANCE',
    title: '集團保險統籌檢視與續保（含 D&O）',
    area: 'RISK',
    category: 'INTERNAL',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 11, day: 30 },
    adjust: 'PREV',
    leadBusinessDays: 45,
    remindDaysBefore: [60, 30, 14],
    owner: 'CFO',
    reviewer: 'LEGAL',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['證券交易法第 39-1 條（董事責任保險應提董事會報告）', '公司內部風險管理政策'],
    outputs: ['保單總表', '保額適足性評估', 'D&O 保險投保情形董事會報告'],
    checklist: [
      ck('財產險、營業中斷險保額與重置成本/獲利能力比對', 'CONFIRM', true),
      ck('產品責任險、運輸險、資安險覆蓋範圍檢視', 'CONFIRM', true),
      ck('董事及重要職員責任保險（D&O）之保額、除外條款與新任董事納保', 'CONFIRM', true),
      ck('D&O 投保金額、承保範圍及保險費率提董事會報告', 'APPROVAL', true),
      ck('理賠案件追蹤與續保條件談判', 'CONFIRM', false),
    ],
  }),
]

/* ═══════════════ 九、永續資訊與氣候相關揭露 ═══════════════ */

export const ESG_OBLIGATIONS: Obligation[] = [
  O({
    id: 'ESG-REPORT',
    title: '永續報告書編製、申報與上傳',
    area: 'ESG',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 8 },
    adjust: 'NEXT',
    leadBusinessDays: 90,
    remindDaysBefore: [120, 60, 30, 14, 7],
    owner: 'ESG_OFFICE',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 4,
    legalBasis: [
      '上市（櫃）公司編製與申報永續報告書作業辦法',
      'GRI 準則 / SASB 產業準則',
    ],
    channel: '公開資訊觀測站（永續報告書專區）',
    outputs: ['永續報告書（中文本，必要時英文本）', '第三方確信/保證意見'],
    checklist: [
      ck('確認本公司適用之申報期限級距（資本額 100 億元以上、鋼鐵及水泥業提前）', 'CONFIRM', true, 'C-ESG-01'),
      ck('重大主題鑑別與利害關係人議合已完成並留存紀錄', 'DOC', true),
      ck('財務相關數據與已公告財報一致', 'RECONCILE', true, 'C-ESG-02'),
      ck('溫室氣體排放量數據來源可追溯，與盤查報告一致', 'RECONCILE', true),
      ck('依規定取得第三方確信（適用者）', 'DOC', false),
      ck('經董事會通過後上傳公開資訊觀測站', 'FILING', true),
    ],
    notes: '本系統預設一般公司為年度終了後 8 個月內；資本額 100 億元以上及鋼鐵、水泥業請於設定調整為 6 個月內。',
  }),
  O({
    id: 'ESG-GHG',
    title: '溫室氣體盤查與查證作業排程',
    area: 'ESG',
    category: 'REGULATORY',
    tiers: ['LISTED', 'OTC'],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 6 },
    adjust: 'PREV',
    leadBusinessDays: 90,
    remindDaysBefore: [120, 60, 30],
    owner: 'ESG_OFFICE',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['上市（櫃）公司永續發展路徑圖', 'ISO 14064-1 / 溫室氣體盤查作業指引'],
    channel: '公開資訊觀測站（溫室氣體排放量資訊）',
    outputs: ['溫室氣體盤查報告書', '查證聲明書'],
    checklist: [
      ck('盤查邊界（組織/營運）與合併報表範圍之差異已說明', 'CONFIRM', true, 'C-ESG-03'),
      ck('範疇一、二排放量計算完成，活動數據可勾稽至費用憑證', 'RECONCILE', true),
      ck('查證機構已委任並完成現場查證', 'CONFIRM', false),
      ck('依規定時程上傳公開資訊觀測站', 'FILING', true),
    ],
  }),
  O({
    id: 'ESG-CLIMATE-FIN',
    title: '氣候相關財務影響評估（IFRS S2 / 情境分析）',
    area: 'ESG',
    category: 'INTERNAL',
    tiers: ['LISTED', 'OTC'],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 4 },
    adjust: 'PREV',
    leadBusinessDays: 60,
    remindDaysBefore: [60, 30, 14],
    owner: 'ESG_OFFICE',
    reviewer: 'CFO',
    approver: 'BOARD',
    severity: 3,
    legalBasis: ['IFRS S1/S2 永續揭露準則接軌時程', '上市上櫃公司永續發展實務守則'],
    outputs: ['氣候風險與機會清冊', '情境分析結果', '財務影響量化說明'],
    checklist: [
      ck('實體風險與轉型風險已辨識並對應至財報科目（資產減損、資本支出、營運成本）', 'DOC', true),
      ck('碳費/碳稅情境下之成本影響已試算', 'DOC', true, 'C-ESG-04'),
      ck('與財報中之重大會計估計（資產耐用年限、減損假設）一致', 'RECONCILE', true),
      ck('提報董事會/永續委員會', 'APPROVAL', true),
    ],
  }),
]
