import type { ChecklistItemDef, Obligation } from './types'
import { ck, withIds } from './obligations.core'

const O = (o: Omit<Obligation, 'checklist'> & { checklist: Omit<ChecklistItemDef, 'id'>[] }): Obligation => ({
  ...o,
  checklist: withIds(o.id, o.checklist),
})

/* ═══════════════ 四、稅務 ═══════════════ */

export const TAX_OBLIGATIONS: Obligation[] = [
  O({
    id: 'TAX-VAT',
    title: '營業稅申報（每 2 個月為 1 期）',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'BIMONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 15 },
    adjust: 'NEXT',
    leadBusinessDays: 6,
    remindDaysBefore: [7, 3, 1],
    owner: 'TAX',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['加值型及非加值型營業稅法第 35 條'],
    penalty: '逾期：滯報金/怠報金，並加徵滯納金與利息',
    channel: '財政部電子申報繳稅服務網',
    outputs: ['營業人銷售額與稅額申報書（401/403）', '進銷項憑證明細'],
    checklist: [
      ck('銷項憑證（電子發票、二聯/三聯式）與帳列營收勾稽', 'RECONCILE', true, 'C-TX-01'),
      ck('零稅率銷售額已備妥出口報單/外匯證明等證明文件', 'DOC', true, 'C-TX-02'),
      ck('進項憑證合法性檢查，不得扣抵項目（交際費、自用乘人小客車等）已剔除', 'CONFIRM', true, 'C-TX-03'),
      ck('視同銷貨（自用、贈與、樣品）已認列', 'CONFIRM', true),
      ck('溢付稅額退稅申請條件確認（外銷/固定資產）', 'CONFIRM', false),
      ck('申報並完成繳納，留存收執聯', 'FILING', true),
    ],
  }),
  O({
    id: 'TAX-WHT-MONTHLY',
    title: '各類所得扣繳稅款繳納（含非居住者）',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'MONTH',
    due: { type: 'MONTHS_AFTER', months: 1, day: 10 },
    adjust: 'NEXT',
    leadBusinessDays: 3,
    remindDaysBefore: [3, 1],
    owner: 'TAX',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['所得稅法第 88 條、第 92 條', '各類所得扣繳率標準'],
    penalty: '未依限扣繳：補繳並處罰鍰（所得稅法第 114 條）',
    channel: '財政部電子申報繳稅服務網',
    outputs: ['扣繳稅額繳款書', '非居住者扣繳申報'],
    checklist: [
      ck('居住者扣繳稅款於次月 10 日前繳納', 'FILING', true, 'C-TX-04'),
      ck('非居住者（含境外電商、權利金、技術服務）扣繳於代扣日起 10 日內繳納並申報', 'FILING', true, 'C-TX-05'),
      ck('租稅協定減免適用者已取得居住者證明與申請核准', 'DOC', false, 'C-TX-05'),
      ck('二代健保補充保費計算與繳納', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'TAX-WHT-ANNUAL',
    title: '各類所得扣繳暨免扣繳憑單、股利憑單申報',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 1, day: 31 },
    adjust: 'NEXT',
    leadBusinessDays: 15,
    remindDaysBefore: [21, 7, 3],
    owner: 'TAX',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['所得稅法第 92 條、第 102-1 條'],
    channel: '財政部電子申報繳稅服務網',
    outputs: ['各類所得扣繳暨免扣繳憑單', '股利憑單', '信託財產收支計算表'],
    checklist: [
      ck('全年給付總額與帳列費用/薪資勾稽', 'RECONCILE', true, 'C-TX-06'),
      ck('所得人資料（身分證號/統編、地址）正確性檢查', 'CONFIRM', true),
      ck('員工薪資、執行業務所得、租金、權利金分類正確', 'CONFIRM', true),
      ck('股利分配之可扣抵資料正確', 'CONFIRM', true),
      ck('完成申報並於期限內將憑單交付所得人', 'FILING', true),
    ],
  }),
  O({
    id: 'TAX-CIT-ANNUAL',
    title: '營利事業所得稅結算申報暨未分配盈餘申報',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 5 },
    adjust: 'NEXT',
    leadBusinessDays: 40,
    remindDaysBefore: [45, 21, 7, 3, 1],
    owner: 'TAX',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 5,
    legalBasis: [
      '所得稅法第 71 條（結算申報）',
      '所得稅法第 66-9 條（未分配盈餘加徵 5%）',
      '營利事業所得稅查核準則',
    ],
    penalty: '逾期：滯報金（應納稅額 10%，上限 3 萬）／怠報金；短漏報處 2 倍以下罰鍰',
    channel: '財政部電子申報繳稅服務網（多採會計師稅務簽證申報）',
    outputs: ['營利事業所得稅結算申報書', '未分配盈餘申報書', '稅務簽證報告書'],
    checklist: [
      ck('帳外調整（交際費、職工福利、折舊、呆帳）逐項複核', 'RECONCILE', true, 'C-TX-07'),
      ck('前十年虧損扣除額適用條件確認（須會計師簽證且如期申報）', 'CONFIRM', true, 'C-TX-08'),
      ck('投資抵減、研發費用加計減除等租稅優惠申請文件備妥', 'DOC', false),
      ck('國外稅額扣抵限額計算與納稅憑證取得', 'DOC', false),
      ck('關係人交易之常規交易性質已於申報書揭露（TP 揭露表）', 'CONFIRM', true, 'C-TX-09'),
      ck('受控外國企業（CFC）當年度所得計算與申報', 'CONFIRM', false, 'C-TX-10'),
      ck('未分配盈餘之減除項目（法定盈餘公積、已分配股利、實質投資）確認', 'CONFIRM', true),
      ck('遞延所得稅與當期所得稅費用與財報數勾稽', 'RECONCILE', true),
      ck('完成申報並繳納稅款', 'FILING', true),
    ],
  }),
  O({
    id: 'TAX-CIT-PROVISIONAL',
    title: '營利事業所得稅暫繳申報',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'FIXED_IN_PERIOD', month: 9, day: 30 },
    adjust: 'NEXT',
    leadBusinessDays: 10,
    remindDaysBefore: [21, 7, 3],
    owner: 'TAX',
    reviewer: 'ACCOUNTING',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['所得稅法第 67 條、第 68 條'],
    penalty: '逾期加徵滯納金與利息',
    channel: '財政部電子申報繳稅服務網',
    outputs: ['營利事業所得稅暫繳申報書'],
    checklist: [
      ck('選擇暫繳方式：前一年度稅額二分之一 或 上半年實際所得試算', 'CONFIRM', true, 'C-TX-11'),
      ck('採試算方式者須經會計師查核簽證並具備條件', 'CONFIRM', false),
      ck('資金已備妥，繳款排入現金流量預測', 'CONFIRM', true),
      ck('完成申報並繳納', 'FILING', true),
    ],
  }),
  O({
    id: 'TAX-TP-DOC',
    title: '移轉訂價三層文據備妥（Master File / Local File / CbCR）',
    area: 'TAX',
    category: 'STATUTORY',
    tiers: [],
    period: 'YEAR',
    due: { type: 'MONTHS_AFTER', months: 5 },
    adjust: 'NEXT',
    leadBusinessDays: 60,
    remindDaysBefore: [60, 30, 14],
    owner: 'TAX',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 4,
    legalBasis: ['營利事業所得稅不合常規移轉訂價查核準則'],
    penalty: '未備妥文據遭調整補稅並處罰鍰',
    channel: '結算申報時揭露；主檔報告與國別報告依規定期限申報',
    outputs: ['移轉訂價報告（Local File）', '集團主檔報告（Master File）', '國別報告（CbCR）'],
    checklist: [
      ck('受控交易彙總（貨物、勞務、資金、無形資產）完整', 'DOC', true, 'C-TX-09'),
      ck('可比較對象搜尋與常規交易區間更新', 'DOC', true),
      ck('本年度實際利潤率落於常規區間內，否則評估年度末調整', 'CONFIRM', true, 'C-TX-09'),
      ck('主檔報告與國別報告之申報門檻判斷與申報', 'CONFIRM', true),
      ck('集團移轉訂價政策與實際交易條件一致', 'CONFIRM', true),
    ],
  }),
  O({
    id: 'TAX-ETR-REVIEW',
    title: '有效稅率與稅務風險季度檢討',
    area: 'TAX',
    category: 'INTERNAL',
    tiers: [],
    period: 'QUARTER',
    due: { type: 'DAYS_AFTER', days: 40 },
    adjust: 'PREV',
    leadBusinessDays: 10,
    remindDaysBefore: [10, 3],
    owner: 'TAX',
    reviewer: 'CFO',
    approver: 'CFO',
    severity: 3,
    legalBasis: ['公司內部稅務管理辦法', 'IAS 12 所得稅'],
    outputs: ['有效稅率調節表', '不確定稅務部位（UTP）清單'],
    checklist: [
      ck('有效稅率與法定稅率調節，重大差異項目說明', 'RECONCILE', true, 'C-TX-12'),
      ck('不確定稅務部位重新評估並調整負債準備', 'CONFIRM', true),
      ck('進行中之稅務查核/行政救濟進度更新', 'CONFIRM', true),
      ck('全球最低稅負（GloBE / 台灣 AMT）影響評估', 'CONFIRM', false, 'C-TX-13'),
    ],
  }),
]
