import type { CheckRule } from './types'

/**
 * 檢核規則庫
 * 每條規則 = 指標算式 + 比較子 + 門檻（可為算式）。
 * threshold / warn 使用算式，讓公司政策參數（policy*）能直接被引用，
 * 修改設定即可全面生效，不需改程式。
 */
export const CHECK_RULES: CheckRule[] = [
  /* ── 融資契約財務約定 ── */
  {
    id: 'CV-01',
    name: '流動比率不低於 120%',
    area: 'TREASURY',
    category: 'COVENANT',
    expression: 'currentRatio',
    comparator: '>=',
    threshold: '120',
    warn: '135',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 5,
    basis: '聯合授信合約財務約定條款（示範值，請依實際合約設定）',
    remediation: '提前處分短期投資、展延短期借款為中長期、暫緩非必要資本支出；緩衝不足時提前與管理行洽談。',
  },
  {
    id: 'CV-02',
    name: '負債比率不高於 60%',
    area: 'TREASURY',
    category: 'COVENANT',
    expression: 'debtRatio',
    comparator: '<=',
    threshold: '60',
    warn: '55',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 5,
    basis: '聯合授信合約財務約定條款（示範值）',
    remediation: '評估增資、盈餘保留或處分非核心資產；控管新增借款。',
  },
  {
    id: 'CV-03',
    name: '利息保障倍數不低於 3 倍',
    area: 'TREASURY',
    category: 'COVENANT',
    expression: 'interestCoverage',
    comparator: '>=',
    threshold: '3',
    warn: '4',
    unit: 'TIMES',
    frequency: 'QUARTER',
    severity: 5,
    basis: '聯合授信合約財務約定條款（示範值）',
    remediation: '降低有息負債或改善營業利益；必要時洽談豁免（Waiver）。',
  },
  {
    id: 'CV-04',
    name: '淨負債/EBITDA 不高於 3.5 倍',
    area: 'TREASURY',
    category: 'COVENANT',
    expression: 'netDebtToEbitda',
    comparator: '<=',
    threshold: '3.5',
    warn: '3',
    unit: 'TIMES',
    frequency: 'QUARTER',
    severity: 4,
    basis: '聯合授信合約財務約定條款（示範值）。EBITDA 採近 12 個月數，與合約定義一致',
    remediation: '控管併購與資本支出節奏，提高自由現金流。',
  },
  {
    id: 'CV-05',
    name: '有形淨值不低於契約下限',
    area: 'TREASURY',
    category: 'COVENANT',
    expression: 'tangibleNetWorth',
    comparator: '>=',
    threshold: '5000000000',
    warn: '6000000000',
    unit: 'AMOUNT',
    frequency: 'QUARTER',
    severity: 5,
    basis: '聯合授信合約「有形淨值」維持條款（示範值 50 億元）',
    remediation: '控管股利發放與庫藏股，避免淨值快速下滑；重大減損前先評估對契約之影響。',
  },

  /* ── 法令與自訂上限 ── */
  {
    id: 'RL-01',
    name: '背書保證總額占淨值比率未超限',
    area: 'TREASURY',
    category: 'REGULATORY_LIMIT',
    expression: 'endorsementToEquity',
    comparator: '<=',
    threshold: 'policyEndorsementPct',
    warn: 'policyEndorsementPct * 0.8',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 5,
    basis: '公開發行公司資金貸與及為他人背書保證處理準則第 12 條，及公司自訂之背書保證處理程序',
    remediation: '立即停止新增背書保證，回收既有保證或提報董事會調整額度並依規定辦理。',
  },
  {
    id: 'RL-02',
    name: '對單一企業背書保證占淨值比率未超限',
    area: 'TREASURY',
    category: 'REGULATORY_LIMIT',
    expression: 'singleEndorsementToEquity',
    comparator: '<=',
    threshold: 'policySingleEndorsementPct',
    warn: 'policySingleEndorsementPct * 0.8',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 5,
    basis: '公司背書保證處理程序所定單一企業限額',
    remediation: '要求被保證公司提供反擔保或降低額度；超限者於發現後依規定期限改善並揭露。',
  },
  {
    id: 'RL-03',
    name: '資金貸與總額占淨值比率未超限',
    area: 'TREASURY',
    category: 'REGULATORY_LIMIT',
    expression: 'lendingToEquity',
    comparator: '<=',
    threshold: 'policyLendingPct',
    warn: 'policyLendingPct * 0.8',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 5,
    basis: '公開發行公司資金貸與及為他人背書保證處理準則第 3 條至第 5 條，及公司自訂之資金貸與作業程序',
    remediation: '停止新增貸與並排定回收；評估是否須提列備抵及發布重大訊息。',
  },
  {
    id: 'RL-04',
    name: '衍生性商品未實現損失未超過內部上限',
    area: 'TREASURY',
    category: 'REGULATORY_LIMIT',
    expression: 'derivativeUnrealizedLoss',
    comparator: '<=',
    threshold: 'equity * 0.02',
    warn: 'equity * 0.01',
    unit: 'AMOUNT',
    frequency: 'MONTH',
    severity: 5,
    basis: '公司從事衍生性商品交易處理程序所定全部/個別契約損失上限（示範值：淨值 2%）',
    remediation: '依內部程序執行停損、平倉，並向董事會報告；達重大標準者發布重大訊息。',
  },
  {
    id: 'RL-05',
    name: '外幣淨曝險占淨值比率未超限',
    area: 'RISK',
    category: 'REGULATORY_LIMIT',
    expression: 'fxExposureToEquity',
    comparator: '<=',
    threshold: '10',
    warn: '7',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 4,
    basis: '公司外匯風險管理辦法（示範值）',
    remediation: '增加遠期外匯或換匯避險部位；檢討自然避險（採購與銷售幣別配對）。',
  },

  /* ── 帳務勾稽（差異須為零）── */
  {
    id: 'RC-01',
    name: '現金流量表期末現金 = 資產負債表現金',
    area: 'REPORTING',
    category: 'RECONCILIATION',
    expression: 'cashDiff',
    comparator: 'ABS<=',
    threshold: '0',
    unit: 'AMOUNT',
    frequency: 'QUARTER',
    severity: 5,
    basis: 'IAS 7 現金流量表；財報編製基本勾稽',
    remediation: '追查受限制現金分類、匯率影響數與現金流量表編製底稿，於申報前務必軋平。',
  },
  {
    id: 'RC-02',
    name: '銀行對帳單餘額 = 帳列非受限現金',
    area: 'TREASURY',
    category: 'RECONCILIATION',
    expression: 'bankCashDiff',
    comparator: 'ABS<=',
    threshold: '0',
    warn: '1000000',
    unit: 'AMOUNT',
    frequency: 'MONTH',
    severity: 5,
    basis: '內部控制—資金循環（銀行調節表）',
    remediation: '逐筆列示未達帳項並取得憑證；差異無法解釋者列為重大缺失並通報稽核。',
  },

  /* ── 分析性覆核 ── */
  {
    id: 'AN-01',
    name: 'DSO 較前期增加不超過 15 天',
    area: 'REPORTING',
    category: 'ANALYTICAL',
    expression: 'dsoDelta',
    comparator: '<=',
    threshold: '15',
    warn: '8',
    unit: 'DAYS',
    frequency: 'QUARTER',
    severity: 3,
    basis: '分析性覆核程序；營收認列與收款異常之早期訊號',
    remediation: '檢視是否有塞貨、放寬授信或收款惡化；覆核備抵呆帳是否充足。',
  },
  {
    id: 'AN-02',
    name: 'DIO 較前期增加不超過 20 天',
    area: 'REPORTING',
    category: 'ANALYTICAL',
    expression: 'dioDelta',
    comparator: '<=',
    threshold: '20',
    warn: '10',
    unit: 'DAYS',
    frequency: 'QUARTER',
    severity: 3,
    basis: '分析性覆核程序；存貨跌價風險之早期訊號',
    remediation: '檢視呆滯存貨與跌價損失提列；調整採購與生產計畫。',
  },
  {
    id: 'AN-03',
    name: '毛利率變動不超過 3 個百分點',
    area: 'REPORTING',
    category: 'ANALYTICAL',
    expression: 'grossMarginDelta',
    comparator: 'ABS<=',
    threshold: '3',
    warn: '2',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 3,
    basis: '分析性覆核程序',
    remediation: '拆解產品組合、售價、原料成本與產能利用率影響，備妥對外說明口徑。',
  },
  {
    id: 'AN-04',
    name: '盈餘品質（營運現金流/淨利）不低於 0.6',
    area: 'REPORTING',
    category: 'ANALYTICAL',
    expression: 'cashQuality',
    comparator: '>=',
    threshold: '0.6',
    warn: '0.9',
    unit: 'TIMES',
    frequency: 'QUARTER',
    severity: 4,
    basis: '盈餘品質分析；獲利與現金流長期背離為財報警訊',
    remediation: '分析營運資金增減與非現金損益；若因應收/存貨堆積所致，須同步檢討評價與收款。',
  },
  {
    id: 'AN-05',
    name: '關係人銷貨占比不超過 30%',
    area: 'COMPLIANCE',
    category: 'ANALYTICAL',
    expression: 'relatedPartySalesPct',
    comparator: '<=',
    threshold: '30',
    warn: '20',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 4,
    basis: '關係人交易揭露與非常規交易風險（IAS 24；取得或處分資產處理準則）',
    remediation: '確認交易條件之常規性與訂價依據；強化揭露並提報審計委員會。',
  },
  {
    id: 'AN-06',
    name: '有效稅率偏離法定稅率不超過 5 個百分點',
    area: 'TAX',
    category: 'ANALYTICAL',
    expression: 'etrGap',
    comparator: 'ABS<=',
    threshold: '5',
    warn: '3',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 3,
    basis: 'IAS 12 所得稅費用調節；稅務風險早期偵測',
    remediation: '編製有效稅率調節表逐項說明；異常項目確認是否須提列不確定稅務部位負債。',
  },

  /* ── 流動性與資金安全 ── */
  {
    id: 'LQ-01',
    name: '未動用授信額度可支應 3 個月以上營運資金',
    area: 'TREASURY',
    category: 'LIQUIDITY',
    expression: 'liquidityMonths',
    comparator: '>=',
    threshold: '3',
    warn: '4',
    unit: 'TIMES',
    frequency: 'MONTH',
    severity: 5,
    basis: '公司資金管理辦法所定最低流動性準備',
    remediation: '洽談新增額度或發行短票；延後非必要支出並加速收款。',
  },
  {
    id: 'LQ-02',
    name: '速動比率不低於 80%',
    area: 'TREASURY',
    category: 'LIQUIDITY',
    expression: 'quickRatio',
    comparator: '>=',
    threshold: '80',
    warn: '100',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 4,
    basis: '公司資金管理辦法（示範值）',
    remediation: '控管存貨與應收，調整短期負債結構。',
  },
  {
    id: 'LQ-03',
    name: '單一銀行存款集中度不超過 30%',
    area: 'RISK',
    category: 'LIQUIDITY',
    expression: 'bankConcentration',
    comparator: '<=',
    threshold: '30',
    warn: '25',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 3,
    basis: '交易對手風險分散政策',
    remediation: '分散存款至其他往來銀行；評估對手信用評等。',
  },
  {
    id: 'RK-01',
    name: '逾期 90 天以上應收占比不超過 5%',
    area: 'RISK',
    category: 'ANALYTICAL',
    expression: 'arOver90Pct',
    comparator: '<=',
    threshold: '5',
    warn: '3',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 4,
    basis: 'IFRS 9 預期信用損失；內部授信管理辦法',
    remediation: '啟動催收/法務程序，凍結該客戶出貨，重新評估備抵呆帳。',
  },
  {
    id: 'RK-02',
    name: '單一客戶應收集中度不超過 25%',
    area: 'RISK',
    category: 'ANALYTICAL',
    expression: 'customerConcentration',
    comparator: '<=',
    threshold: '25',
    warn: '20',
    unit: 'PCT',
    frequency: 'MONTH',
    severity: 4,
    basis: '信用風險集中度管理政策',
    remediation: '投保輸出保險或應收帳款承購；要求擔保或縮短帳期。',
  },
  {
    id: 'RK-03',
    name: '呆滯存貨（庫齡逾一年）占比不超過 10%',
    area: 'RISK',
    category: 'ANALYTICAL',
    expression: 'inventoryAgingPct',
    comparator: '<=',
    threshold: '10',
    warn: '7',
    unit: 'PCT',
    frequency: 'QUARTER',
    severity: 3,
    basis: '存貨評價與跌價損失提列政策',
    remediation: '提列跌價損失、安排出清或報廢程序並經權責核准。',
  },
]

export const RULE_MAP: Record<string, CheckRule> = Object.fromEntries(CHECK_RULES.map((r) => [r.id, r]))
